CREATE TABLE employment_type
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(50)                             NOT NULL,
    sort_order INTEGER,
    CONSTRAINT pk_employment_type PRIMARY KEY (id)
);

CREATE TABLE jobs
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(50)                             NOT NULL,
    sort_order INTEGER,
    CONSTRAINT pk_jobs PRIMARY KEY (id)
);

CREATE TABLE positions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(50)                             NOT NULL,
    sort_order INTEGER,
    CONSTRAINT pk_positions PRIMARY KEY (id)
);

CREATE TABLE ranks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(50)                             NOT NULL,
    sort_order INTEGER,
    CONSTRAINT pk_ranks PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    token_hash VARCHAR(64)                             NOT NULL,
    expiration TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE user_organizations
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT,
    organization_id   BIGINT                                  NOT NULL,
    organization_name VARCHAR(100)                            NOT NULL,
    is_primary        BOOLEAN                                 NOT NULL,
    is_leader         BOOLEAN                                 NOT NULL,
    assigned_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_organizations PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR(100)                            NOT NULL,
    email                VARCHAR(100)                            NOT NULL,
    password             VARCHAR(255)                            NOT NULL,
    phone                VARCHAR(100),
    address              VARCHAR(100),
    join_date            date                                    NOT NULL,
    work_years           INTEGER,
    is_admin             BOOLEAN                                 NOT NULL,
    needs_password_reset BOOLEAN,
    employment_type_wid  BIGINT,
    rank_id              BIGINT,
    position_id          BIGINT,
    job_id               BIGINT,
    role                 VARCHAR(100),
    profile_image_url    VARCHAR(500),
    work_policy_id       BIGINT,
    self_introduction    TEXT,
    last_login_at        TIMESTAMP WITHOUT TIME ZONE,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE employment_type
    ADD CONSTRAINT uc_employment_type_name UNIQUE (name);

ALTER TABLE jobs
    ADD CONSTRAINT uc_jobs_name UNIQUE (name);

ALTER TABLE positions
    ADD CONSTRAINT uc_positions_name UNIQUE (name);

ALTER TABLE ranks
    ADD CONSTRAINT uc_ranks_name UNIQUE (name);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_userid UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_EMPLOYMENT_TYPE_WID FOREIGN KEY (employment_type_wid) REFERENCES employment_type (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_JOB FOREIGN KEY (job_id) REFERENCES jobs (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_POSITION FOREIGN KEY (position_id) REFERENCES positions (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_RANK FOREIGN KEY (rank_id) REFERENCES ranks (id);

ALTER TABLE user_organizations
    ADD CONSTRAINT FK_USER_ORGANIZATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);