CREATE TABLE user_tenants
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email     VARCHAR(100)                            NOT NULL,
    tenant_id VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_user_tenants PRIMARY KEY (id)
);

ALTER TABLE user_tenants
    ADD CONSTRAINT uc_user_tenants_email UNIQUE (email);

CREATE INDEX idx_user_tenants_email ON user_tenants (email);